import time
import pyfiglet
import color
from colorama import init, Fore
init()

red = '\033[31m'
blue = '\033[36m'
green = '\033[32m'
darkblue = '\033[34m'
pink = '\033[35m'
yellow = '\033[93m'
white = '\033[00m'

print("HACKED  /OF/  TELEGRAM")
print("")
print("DKI-KALANTAR")
print(Fore.RED+'                   ☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.GREEN+'                 》       DKI-KALANTAR      《')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ♡                     ☆ ')
print(Fore.RED+'                   ☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆♡☆ ')
print(Fore.BLUE+'</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>')
print(Fore.YELLOW+'         telegram : PV_MARSHAL ')
print(Fore.RED+'         GITHUB : https://github.com/mr-pydroid ')
print('\033[93m         BLOG : reeve.blog.ir ')
print(Fore.BLUE+'</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>!</>!<\>')
print("")
print("")
print("")
print("")
print("")
time.sleep(2)
print("\033[36m HACK LOADING......")
print("")
time.sleep(1)
print("")
print("\033[35m NUMBER +TEL : +989055706271")
print("")
time.sleep(1)
print("\033[31m RUN HACK")
print("")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("                      ^                    °°°")
time.sleep(1)
print("°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
time.sleep(1)
print("°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°")
print("\033[32m FiNiSheD")
print("The hacking operation was successful !")
time.sleep(2)
print("\033[93m HACK NAME : HACK TELEGRAM")
time.sleep(1)
print("NAME OF PLATFORM : ACCOUNT TELEGRAM")
time.sleep(1)
print("PLATFORM : TELEGRAM")
time.sleep(1)
print("CODE NUMBER : +98")
time.sleep(1)
print("LOCATION : IR-IRAN")
time.sleep(1)
print("PASSWORD : g8Hp05hJpQ3")
time.sleep(1)
print("\033[00m The operation is over")
